--- 
title: "Open Trade Statistics"
author: "Pachá (Mauricio Vargas Sepúlveda)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [references.bib]
link-citations: yes
github-repo: tradestatistics/documentation
---

# About

## Project goals

Open Trade Statistics is an independent project that values reproducible research and provides tidy trade data. We are heavily inspired by R community values and Open Licenses views on freedom.

We focus on commodities data and our added value, unlike many other good trade data projects, is that we focus on data processing and reproducibilidy instead of data visualization.

Our goal is to ease data analysis and promote a reproducibility culture.

We advocate for openness and collaboration, so our contribution is focused on:

* Releasing all of our source code on GitHub
* Releasing snapshots of the software we use
* Sharing curated data (direct download and API)

## Data availability

We used different trade classifications according to the data availability.

|Classification |Availability|
|---------------|------------|
|HS rev 1992    |1992 – 2017 |
|HS rev 1996    |1996 – 2017 |
|HS rev 2002    |2002 – 2017 |
|HS rev 2007    |2007 – 2017 |
|SITC rev 1     |1962 – 2017 |
|SITC rev 2     |1976 – 2017 |

These datasets were used all together in order to create a unified data series for the period 1962-2017 with all products classified under HS rev 2007.

## Sources

All of the product data shown on the OTS site is classified using either SITC (Standard International Trade Classification) or HS (Harmonized System), the raw data was obtained from [UN COMTRADE](http://comtrade.un.org/) and its under their authorization that we share claned versions of the original raw datasets.

## Code

We made all the scripts available on [GitHub](https://github.com/tradestatistics). Pull requests and new ideas are always welcome!

## Contact

Follow us on Twitter! Our username is [\@opentradestats](https://twitter.com/opentradestats).

## Donate

You can also help offset our hosting costs by donating via [PayPal](https://paypal.me/tradestatistics).
